name: laza
description: "Personalized E-Commerce Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^18.0.1
  get_it: ^9.3.0
  dio: ^5.11.1
  flutter_svg: ^2.3.0
  json_annotation: ^4.12.0
  freezed_annotation: ^3.1.0
  cached_network_image: ^4.0.2
  shimmer: ^4.0.0
  shared_preferences: ^2.5.5
  flutter_countdown_timer: ^4.1.0
  intl: ^0.20.3
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  easy_debounce: ^2.0.3
  visibility_detector: ^0.4.0+2
  firebase_core: ^4.15.0
  firebase_crashlytics: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.13.0+1
  freezed: ^4.0.2
  json_serializable: ^6.14.1
  build_runner: ^2.16.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
