// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiWlXD0YAZxEfBHWDfHSD--GZo7D_xqA4',
    appId: '1:974877262639:web:c84af3a905710f47dad7da',
    messagingSenderId: '974877262639',
    projectId: 'laza-0710',
    authDomain: 'laza-0710.firebaseapp.com',
    storageBucket: 'laza-0710.firebasestorage.app',
    measurementId: 'G-ZL69HF3M91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgOBNl5v-Ff8ssB3QwaI77D9Y_Wr2Qqtg',
    appId: '1:974877262639:android:0c6405a439160161dad7da',
    messagingSenderId: '974877262639',
    projectId: 'laza-0710',
    storageBucket: 'laza-0710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCpcaeE0d7i6x6lFzT_kLzeGXjGhcBOU',
    appId: '1:974877262639:ios:fbbf3f18eb9f9c57dad7da',
    messagingSenderId: '974877262639',
    projectId: 'laza-0710',
    storageBucket: 'laza-0710.firebasestorage.app',
    iosBundleId: 'com.digitalsalt.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsCpcaeE0d7i6x6lFzT_kLzeGXjGhcBOU',
    appId: '1:974877262639:ios:fbbf3f18eb9f9c57dad7da',
    messagingSenderId: '974877262639',
    projectId: 'laza-0710',
    storageBucket: 'laza-0710.firebasestorage.app',
    iosBundleId: 'com.digitalsalt.laza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiWlXD0YAZxEfBHWDfHSD--GZo7D_xqA4',
    appId: '1:974877262639:web:c2637945009b654ddad7da',
    messagingSenderId: '974877262639',
    projectId: 'laza-0710',
    authDomain: 'laza-0710.firebaseapp.com',
    storageBucket: 'laza-0710.firebasestorage.app',
    measurementId: 'G-N9Q3QEE0P1',
  );
}
